[build]
  command = "npm run build"
  publish = "dist"
  environment = { NPM_FLAGS = "--include=optional" }

[context.production]
  # environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }

[[redirects]]
  from = "/syntrons"
  to = "/en/research/syntron"
  status = 301

[[redirects]]
  from = "/trafp-odc"
  to = "/en/research/trafpodc"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"