[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[template.environment]
  REACT_APP_API_URL = "Your API URL"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/syntrons"
  to = "/en/research/syntron"
  status = 301

[[redirects]]
  from = "/trafp-odc"
  to = "/en/research/trafpodc"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[template]
  [template.contact]
    subject = "New contact form submission from Abderrahim Kaci Chaouche website"
    to = "abdelrahim.kacich@gmail.com"